# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9930f24d9bdf9aee8b7899f4c529a0a20c347f5ebbe9170ee8b25db2cd4efbdd7b8d03cfbf388a6b2648268e5eb67e03fb99416ea278c69a351cb6570ebabb5

test:
  secret_key_base: b55aa6abc13d150626b6990fdc9705d59bbf08f76b57c25ee7b388f272fcca2165833b4472e0dcea67ed91d0ace3a908ad09ed41080248cf4a3aae28924f2ddb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
